# Generated by Django 5.2.7 on 2025-11-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('tenant_name', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=20)),
                ('rent_price', models.IntegerField()),
                ('old_electric', models.IntegerField()),
                ('new_electric', models.IntegerField()),
                ('electric_price', models.IntegerField(default=4000)),
                ('water_fee', models.IntegerField(default=0)),
                # ('internet_fee', models.IntegerField(default=0)),
                ('other_fee', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
