# Generated by Django 5.2.7 on 2025-11-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentrecord',
            name='rent_price',
            field=models.IntegerField(default=3000000),
        ),
        migrations.AlterField(
            model_name='rentrecord',
            name='water_fee',
            field=models.IntegerField(default=200000),
        ),
    ]
