# Generated by Django 5.2.7 on 2025-11-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_record', '0002_alter_rentrecord_rent_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentrecord',
            name='other_fee',
            field=models.IntegerField(default=65000),
        ),
    ]
